FROM ghcr.io/opentofu/opentofu:1.8.8 AS tofu-source
FROM ubuntu:24.04

# Installa psmisc per avere il comando 'killall' necessario al riavvio del processo
RUN apt-get update && apt-get install -y psmisc wget ca-certificates vim && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    ca-certificates \
    --no-install-recommends \
    && wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" \
       > /etc/apt/sources.list.d/google-chrome.list \
    && apt-get update && apt-get install -y \
    google-chrome-stable \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copiamo il primo binario compilato
COPY ./bin/manager /manager

COPY --from=tofu-source /usr/local/bin/tofu /usr/local/bin/tofu
COPY terraform/ /terraform-templates

RUN chmod +x /manager

#USER 65532:65532
# Lanciamo l'applicazione
CMD ["/bin/sh", "-c", "while true; do /manager; echo 'restarting...'; sleep 1; done"]