apiVersion: k8s.dinova.one/v1
kind: FortigateFirewall
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator-fortigate
    app.kubernetes.io/managed-by: kustomize
  name: fortigatefirewall-trial
spec:
  pvcStorageClass: <STORAGE_CLASS>
  version: "2026.03"
  type: "vyos"
  hasCloudInit: false
  ports:
    - name: "port1"
      index: 0
      networkName: "linux-bridge-net-ipam"