---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.dinova.one
  resources:
  - firewallconfigs
  - firewalls
  - fortigatebackups
  - fortigateconfigs
  - fortigatefirewalls
  - fortigateupdatepaths
  - fortigateupdates
  - nodebridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.dinova.one
  resources:
  - firewallconfigs/finalizers
  - firewalls/finalizers
  - fortigatebackups/finalizers
  - fortigateconfigs/finalizers
  - fortigatefirewalls/finalizers
  - fortigateupdatepaths/finalizers
  - fortigateupdates/finalizers
  - nodebridges/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.dinova.one
  resources:
  - firewallconfigs/status
  - firewalls/status
  - fortigatebackups/status
  - fortigateconfigs/status
  - fortigatefirewalls/status
  - fortigateupdatepaths/status
  - fortigateupdates/status
  - nodebridges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines/restart
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - snapshot.kubevirt.io
  resources:
  - virtualmachinesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - subresources.kubevirt.io
  resources:
  - virtualmachines/migrate
  - virtualmachines/pause
  - virtualmachines/restart
  - virtualmachines/start
  - virtualmachines/stop
  - virtualmachines/unpause
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
